# .github/workflows/publish-testpypi.yml
name: Publish to Test PyPI

on:
  push:
    branches: [main]          # run on every commit to main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry & Twine
        run: pip install poetry twine

      - name: Build package
        run: |
          rm -rf dist/
          poetry install
          poetry build

      - name: Upload to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
